In [1]:
import numpy as np
from numpy import linalg as lg

# Madhusmita Mukherjee 20BCE2783

In [2]:
a = np.array([[3,2,-1],[6,8,-7],[4,4,0]])

In [3]:
b = np.array([[5,-3,7],[1,0,-6],[-4,8,9]])

In [4]:
a + b         # Matrix Addition

array([[  8,  -1,   6],
       [  7,   8, -13],
       [  0,  12,   9]])

In [5]:
a = np.array([[3,2,-1],[6,8,-7],[4,4,0]])

In [6]:
b = np.array([[5,-3,7],[1,0,-6],[-4,8,9]])

In [7]:
np.matmul(a,b)    # Matrix Multiplication

array([[ 21, -17,   0],
       [ 66, -74, -69],
       [ 24, -12,   4]])

In [8]:
a = np.array([[3,2,-1],[6,8,-7],[4,4,0]])

In [9]:
c = lg.det(a)    # Determinant of matrix
c

36.0

In [10]:
b = np.array([[5,-3,7],[1,0,-6],[-4,8,9]])

In [11]:
lg.matrix_rank(b)       # Rank of a matrix

3

In [12]:
v = np.array([[3,2],[1,4],[5,3]])

In [13]:
lg.matrix_rank(v)

2

In [14]:
a = np.array([[3,2,-1],[6,8,-7],[4,4,0]])

In [15]:
lg.inv(a)     # Multiplicative Inverse of matrix

array([[ 0.77777778, -0.11111111, -0.16666667],
       [-0.77777778,  0.11111111,  0.41666667],
       [-0.22222222, -0.11111111,  0.33333333]])

In [16]:
k = np.array([[1,3,2],[-1,2,-3],[-2,4,-6]])
k

array([[ 1,  3,  2],
       [-1,  2, -3],
       [-2,  4, -6]])

In [17]:
lg.det(k)

0.0

Q3 and q4

In [18]:
a = np.array([[1,0,-1], [1,0,0],[-2,2,1]])
a

array([[ 1,  0, -1],
       [ 1,  0,  0],
       [-2,  2,  1]])

In [19]:
eigenValues, eigenVectors = lg.eig(a)

In [20]:
eigenValues

array([ 2., -1.,  1.])

In [21]:
eigenVectors

array([[ 6.66666667e-01,  4.08248290e-01,  7.07106781e-01],
       [ 3.33333333e-01, -4.08248290e-01,  7.07106781e-01],
       [-6.66666667e-01,  8.16496581e-01,  5.66950743e-17]])

In [22]:
f = np.array([[2,2,-2,-2], [0,0,2,2],[4,2,-8,6],[-6,-2,12,8]])
f

array([[ 2,  2, -2, -2],
       [ 0,  0,  2,  2],
       [ 4,  2, -8,  6],
       [-6, -2, 12,  8]])

In [23]:
eigenValues, eigenVectors = lg.eig(f)

In [24]:
eigenValues

array([-11.47312601,  12.16116686,   2.        ,  -0.68804085])

In [25]:
eigenVectors

array([[-0.05923418, -0.19455653,  0.7570333 , -0.69093692],
       [ 0.05923418,  0.19455653,  0.48666426,  0.69093692],
       [-0.85373157,  0.25644843,  0.43259046, -0.21094208],
       [ 0.51393095,  0.92656879,  0.05407381, -0.02675433]])

In [26]:
v = np.array([[3,2],[1,4],[5,3]])
v

array([[3, 2],
       [1, 4],
       [5, 3]])