In [1]:

# Madhusmita Mukherjee 20BCE2783
# cholesky decomposition

import numpy as np
from numpy import linalg as lg

a = np.array([[6,15,55],[15,55,225],[55,225,979]])
# b = np.array([[0,1,-2],[-1,0,3],[2,-3,0]]) #not symmetric
# c = np.array([[2,3],[4,6],[7,9]]) #not a square matrix
# d = np.array([[-3,2,0],[2,-3,0],[0,0,-5]]) #not a positive definite
print("The matrix formed is :")
print(a)

L = lg.cholesky(a)
print("\nL is :")
print(L)

Lt = L.T.conj()
print("\nLT is :")
print(Lt)

np.dot(L, Lt) # to verify that L * L.T = a

The matrix formed is :
[[  6  15  55]
 [ 15  55 225]
 [ 55 225 979]]

L is :
[[ 2.44948974  0.          0.        ]
 [ 6.12372436  4.18330013  0.        ]
 [22.45365598 20.91650066  6.11010093]]

LT is :
[[ 2.44948974  6.12372436 22.45365598]
 [ 0.          4.18330013 20.91650066]
 [ 0.          0.          6.11010093]]


array([[  6.,  15.,  55.],
       [ 15.,  55., 225.],
       [ 55., 225., 979.]])

In [2]:
# Madhusmita Mukherjee 20BCE2783
# eigen decomposition

import numpy as np
from numpy import linalg as lg

A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Matrix is: \n",A)

vals, vectors = lg.eig(A)
print("\nEigen-values are : \n",vals)
print("\nEigen-vectors Of Matrix A : \n",vectors)

P = vectors
print("\nMatrix Formed By EigenVectors : \n",P)
Pinv = lg.inv(P)
print("\nInverse Of EigenVectors Matrix Is : \n",Pinv)
D = np.diag(vals)
print("\nDiagonal Matrix Formed By EigenValues : \n",D)

B = P.dot(D).dot(Pinv)  # Reconstructing Original Matrix A    # B = P D P^-1
print("\nOrignial Matrix is: \n",B) # B is A

Matrix is: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Eigen-values are : 
 [ 1.61168440e+01 -1.11684397e+00 -3.38433605e-16]

Eigen-vectors Of Matrix A : 
 [[-0.23197069 -0.78583024  0.40824829]
 [-0.52532209 -0.08675134 -0.81649658]
 [-0.8186735   0.61232756  0.40824829]]

Matrix Formed By EigenVectors : 
 [[-0.23197069 -0.78583024  0.40824829]
 [-0.52532209 -0.08675134 -0.81649658]
 [-0.8186735   0.61232756  0.40824829]]

Inverse Of EigenVectors Matrix Is : 
 [[-0.48295226 -0.59340999 -0.70386772]
 [-0.91788599 -0.24901003  0.41986593]
 [ 0.40824829 -0.81649658  0.40824829]]

Diagonal Matrix Formed By EigenValues : 
 [[ 1.61168440e+01  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00 -1.11684397e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00 -3.38433605e-16]]

Orignial Matrix is: 
 [[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


In [3]:
C = np.array([[1,0,-1],[1,0,0],[-2,2,1]])
print("Matrix is: \n",C)
vals, vectors = lg.eig(C)
print("\nEigen-values are : \n",vals)
print("\nEigen-vectors Of Matrix : \n",vectors)
P = vectors
print("\nMatrix Formed By EigenVectors : \n",P)
Pinv = lg.inv(P)
print("\nInverse Of EigenVectors Matrix Is : \n",Pinv)
D = np.diag(vals)
print("\nDiagonal Matrix Formed By EigenValues : \n",D)

B = P.dot(D).dot(Pinv)
print("\nOrignial Matrix is: \n",B)

Matrix is: 
 [[ 1  0 -1]
 [ 1  0  0]
 [-2  2  1]]

Eigen-values are : 
 [ 2. -1.  1.]

Eigen-vectors Of Matrix : 
 [[ 6.66666667e-01  4.08248290e-01  7.07106781e-01]
 [ 3.33333333e-01 -4.08248290e-01  7.07106781e-01]
 [-6.66666667e-01  8.16496581e-01  5.66950743e-17]]

Matrix Formed By EigenVectors : 
 [[ 6.66666667e-01  4.08248290e-01  7.07106781e-01]
 [ 3.33333333e-01 -4.08248290e-01  7.07106781e-01]
 [-6.66666667e-01  8.16496581e-01  5.66950743e-17]]

Inverse Of EigenVectors Matrix Is : 
 [[ 1.         -1.         -1.        ]
 [ 0.81649658 -0.81649658  0.40824829]
 [ 0.          1.41421356  0.70710678]]

Diagonal Matrix Formed By EigenValues : 
 [[ 2.  0.  0.]
 [ 0. -1.  0.]
 [ 0.  0.  1.]]

Orignial Matrix is: 
 [[ 1.00000000e+00 -2.42337678e-16 -1.00000000e+00]
 [ 1.00000000e+00  9.07292297e-17  4.53646149e-17]
 [-2.00000000e+00  2.00000000e+00  1.00000000e+00]]


In [4]:
# Madhusmita Mukherjee
# Singular-Value Decomposition
import numpy as np
from numpy import linalg as lg

A = np.array([[1,0,-1],[1,0,0],[-2,2,1]])
print("A is \n", A)

U, s, VT = lg.svd(A)   # Evaluating SVD  A = U Sigma V(transpose)
print("\nU is: \n",U)
print("\ns is: \n",s)
print("\nVT is: \n",VT)

Sigma = np.zeros((A.shape[0], A.shape[1]))

Sigma[:A.shape[1], :A.shape[1]] = np.diag(s)  # populate Sigma with n x n diagonal matrix

B = U.dot(Sigma.dot(VT))  # Reconstructing matrix
print("\n original matrix is: \n",B)

A is 
 [[ 1  0 -1]
 [ 1  0  0]
 [-2  2  1]]

U is: 
 [[-0.34332443  0.81649658 -0.46417849]
 [-0.2251758   0.40824829  0.88466332]
 [ 0.91182465  0.40824829  0.04369366]]

s is: 
 [3.25936733 1.         0.61361602]

VT is: 
 [[-0.73393063  0.55951021  0.38508979]
 [ 0.40824829  0.81649658 -0.40824829]
 [ 0.54284358  0.14241368  0.82767094]]

 original matrix is: 
 [[ 1.00000000e+00 -1.00515228e-15 -1.00000000e+00]
 [ 1.00000000e+00 -2.87392891e-16 -3.09957227e-16]
 [-2.00000000e+00  2.00000000e+00  1.00000000e+00]]


In [5]:
A = np.array([[1,0,1],[-2,1,0]])
print("A is \n", A)
U, s, VT = lg.svd(A)   # Evaluating SVD  A = U Sigma V(transpose)
print("\nU is: \n",U)
print("\ns is: \n",s)
print("\nVT is: \n",VT)

A is 
 [[ 1  0  1]
 [-2  1  0]]

U is: 
 [[ 0.4472136   0.89442719]
 [-0.89442719  0.4472136 ]]

s is: 
 [2.44948974 1.        ]

VT is: 
 [[ 9.12870929e-01 -3.65148372e-01  1.82574186e-01]
 [-3.90238130e-16  4.47213595e-01  8.94427191e-01]
 [-4.08248290e-01 -8.16496581e-01  4.08248290e-01]]
