1) Substitution method
2) Gauss Jordan 
3) Elimintation method
4) Gaussiam Elimination

Solution of system of linear equations using Substitution Method

In [1]:
# Madhusmita Mukherjee 20BCE2783
def solutionBySubstituion(arr1, arr2):
    x1, y1, c1 = arr1[0], arr1[1], arr1[2]
    x2, y2, c2 = arr2[0], arr2[1], arr2[2]
    tempArr = []
    tempArr.append(x1)
    tempArr.append(-y1)
    tempArr.append(c1)
    resultY = ((tempArr[0]*c2) - (x2*tempArr[2])) / ((x2*tempArr[1]) + (tempArr[0]*y2)) 
    resultX = (c1 - (y1*resultY)) / x1 
    print("x = ", resultX)
    print("y = ", resultY)

In [2]:
# Unique Solution 5 x + 2y = 2; 4 x - 7 y = -9
arr1 = [5, 2, 2]
arr2 = [4, -7, -9]
solutionBySubstituion(arr1, arr2)

x =  -0.09302325581395347
y =  1.2325581395348837


In [3]:
# Unique Solution 3 x + y = -1; 2 x - 3 y = -19
arr1 = [3, 1, -1]
arr2 = [2, -3, -19]
solutionBySubstituion(arr1, arr2)

x =  -2.0
y =  5.0


In [4]:
# No Solution
arr1 = [-4, 10, 6]
arr2 = [2, -5, 3]
solutionBySubstituion(arr1, arr2)

ZeroDivisionError: division by zero

In [5]:
# Infinitely Many solutions
arr1 = [12, 7, 3]
arr2 = [24, 14, 6]
solutionBySubstituion(arr1, arr2)

ZeroDivisionError: division by zero

Gauss Jordan Elimination

In [6]:
import numpy as np
from numpy import linalg as lg
m1 = np.array([[2,5],[3,6]])
m2 = np.array([[20],[12]])
m1_inverse = lg.inv(m1)
soln = np.matmul(m1_inverse, m2)    # X = A^(-1) * B

In [7]:
soln

array([[-20.],
       [ 12.]])

In [8]:
import numpy as np
from numpy import linalg as lg
m1 = np.array([[2,3],[4,6]])
m2 = np.array([[6],[5]])
m1_inverse = lg.inv(m1)
soln = np.matmul(m1_inverse, m2)    # X = A^(-1) * B

LinAlgError: Singular matrix

Elimination Method

In [9]:
# Unique Solution
arr1 = np.array([[2,3],[4,2]])  
arr2 = np.array([3,9])      

In [10]:
ans = lg.solve(arr1, arr2)
ans

array([ 2.625, -0.75 ])

In [11]:
# No Solution
arr1 = np.array([[-3,4],[6,-8]])  
arr2 = np.array([3,6])   
ans = lg.solve(arr1, arr2)
ans

LinAlgError: Singular matrix

In [12]:
# Infinitely many Solution
arr1 = np.array([[-12,11],[-36,33]])  
arr2 = np.array([24,72]) 
ans = lg.solve(arr1, arr2)
ans

array([-1.48029737e-16,  2.18181818e+00])

Gaussian Elimination

In [13]:
# Unique Solution 3 x + y = -1; 2 x - 3 y = -19

arr1 = [3, 1, -1]
arr2 = [2, -3, -19]
new_List1 = [i/arr1[0] for i in arr1] # R1
print(new_List1)
new_List2 = [j/arr2[0] for j in arr2] # R2
print(new_List2)
for i in range(3):
    new_List3[i] = new_List2[i] - new_List1[i] # R2 <- R2 - R1
print(new_List3)
y = new_List3[2] / new_List3[1]
x = new_List1[2] - (y * new_List1[1])
print("")
print("Solution is x = ", x," and y = ", y)

[1.0, 0.3333333333333333, -0.3333333333333333]
[1.0, -1.5, -9.5]


NameError: name 'new_List3' is not defined

In [14]:
# No Solution
arr1 = [-3, 4, 3]
arr2 = [6, -8, 6]
new_List1 = [i/arr1[0] for i in arr1] # R1
print(new_List1)
new_List2 = [j/arr2[0] for j in arr2] # R2
print(new_List2)
for i in range(3):
    new_List3[i] = new_List2[i] - new_List1[i] # R2 <- R2 - R1
print(new_List3)
y = new_List3[2] / new_List3[1]
x = new_List1[2] - (y * new_List1[1])
print("")
print("Solution is x = ", x," and y = ", y)

[1.0, -1.3333333333333333, -1.0]
[1.0, -1.3333333333333333, 1.0]


NameError: name 'new_List3' is not defined

In [15]:
# infinitelY many Solution

arr1 = [-10, 20, 30]
arr2 = [50, -100, -150]
new_List1 = [i/arr1[0] for i in arr1] # R1
print(new_List1)
new_List2 = [j/arr2[0] for j in arr2] # R2
print(new_List2)
for i in range(3):
    new_List3[i] = new_List2[i] - new_List1[i] # R2 <- R2 - R1
print(new_List3)
y = new_List3[2] / new_List3[1]
x = new_List1[2] - (y * new_List1[1])
print("")
print("Solution is x = ", x," and y = ", y)

[1.0, -2.0, -3.0]
[1.0, -2.0, -3.0]


NameError: name 'new_List3' is not defined